### ISSUE TITLE
Add input to select stack definition version to validate

### ISSUE THREAD

**Issue by andyfeller** [sundargs2000/stacks-pre-publish#3]
**Problem Statement**

Stacks is currently staff shipped with its schema versioned at `0.1.0` currently.  As the schema is refined and updated, this version will change, which means that users of this action might need a different version depending on their situation.

**Acceptance Criteria**

1. Add [`inputs`](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs) _(perhaps `stack-version`?)_ with a default value of `0.1.0` that is used to select the appropriate schema file

**Additional**

Thanks for putting this together!  It will be immensely helpful!!! ✨

**Comment by sundargs2000** [comment]
@andyfeller Thanks for the suggestion. There is a [version field](https://github.com/sundargs2000/stacks-pre-publish/blob/e59aeff2d105566505936742ea213c5fda010eb6/schemas/stack_schema-0.1.0.json#L294) in the stack schema itself. I don't think a separate input is required. Do you see any scenario?

**Comment by andyfeller** [comment]
Thanks for the follow up, @sundargs2000!

I do see a scenario but might be a little roundabout to explain:

1. End user A adopts this action while stack version is `0.1.0`
2. GitHub releases changes to create an updated stack version either `0.1.1`, `0.2.0`, or `1.0.0`
3. End user A doesn't change their stack version because they are busy and should be valid still.
3. End user B adopts this action but expects newer stack version is the default

Now you're in a scenario where this action needs to behave differently depending on the user.

Like the [Kubernetes ecosystem and resource versions](https://kubernetes.io/docs/reference/using-api/api-concepts/#resource-versions), I would expect this GitHub Action to be flexible with whatever version the end user needs, which can possibly drift between GHEC, GHES, and GHAE especially if an older version of GHES.

**Comment by sundargs2000** [comment]
@andyfeller so sorry that i missed this.

The thing here i see is when at 3, the end user doesn't have a stack version present in his template and there's a newer version with breaking changes, the stack is actually invalid since a stack without version would assume latest. using that to create a release would fail with validation errors. 

Let me know if this makes sense or I am missing something.

**Comment by andyfeller** [comment]
no worries, @sundargs2000.  I'm thinking in the long term about supporting customers on both GHEC and GHES, which can be at 2 different versions of Stacks potentially in the future.  So the scenario above, User A is on GHES and User B is on GHEC, which might be a few versions ahead because upgrading GHES hasn't been prioritized.

**Comment by andyfeller** [comment]
I'm going to close the issue for now because it isn't a breaking need now, however I can imagine this will come up in the future, so we can let sleeping dogs lie.
